AWSTemplateFormatVersion: "2010-09-09"
Description: Terra Cloud
Resources:
    TerraS3:
        Type: AWS::S3::Bucket
    CloudFrontOriginAccessIdentity:
        Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
        Properties:
             CloudFrontOriginAccessIdentityConfig:
                 Comment: Cloud Front Origin Access
    CloudFront:
        Type: AWS::CloudFront::Distribution
        Properties:
            DistributionConfig:
                Origins:
                    - DomainName:
                      Id: S3Origin
                      S3OriginConfig:
                          OriginAccessIdentity: !Sub
                            - origin-access-identity/cloudfront/${IDOfOriginAccessIdentity}
                            - { IDOfOriginAccessIdentity : !Ref CloudFrontOriginAccessIdentity }
                DefaultCacheBehavior:
                    ForwardedValues:
                        QueryString: FALSE
                    TargetOriginId:
                    ViewerProtocolPolicy:
                Origins:
                Enabled:
    TerraECSCluster:
        Type: AWS::ECS::Cluster
        Properties:
            ClusterName: TerraCluster
    TerraECSService:
        Type: AWS::ECS::Service
        Properties:
            TaskDefinition: !REF TerraECSTaskDefinition
    TerraECSTaskDefinition:
        Type: AWS::ECS::TaskDefinition
        Properties:
            ContainerDefinitions:
                - ContainerDefinition:
                    Name: TerraElasticContainer
                    Image: 498848135448.dkr.ecr.us-east-1.amazonaws.com/terra-repo
