AWSTemplateFormatVersion: "2010-09-09"
Description: Terra Cloud
Parameters:
    BucketNameArgument:
        Type: String
Resources:
    TerraS3:
        Type: AWS::S3::Bucket
        BucketName: !Ref BucketNameArgument
    CloudFrontOriginAccessIdentity:
        Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
        Properties:
             CloudFrontOriginAccessIdentityConfig:
                 Comment: Cloud Front Origin Access
    CloudFront:
        Type: AWS::CloudFront::Distribution
        Properties:
            DistributionConfig:
                Enabled: 'false'
                DefaultCacheBehavior:
                    TargetOriginId: S3Origin
                    ViewerProtocolPolicy: allow-all
                    ForwardedValues:
                        QueryString: 'false'
                Origins:
                - DomainName: !GetAtt [TerraS3, DomainName]
                  Id: S3Origin
                  S3OriginConfig:
                      OriginAccessIdentity: !Sub
                        - origin-access-identity/cloudfront/${IDOfOriginAccessIdentity}
                        - { IDOfOriginAccessIdentity: !Ref CloudFrontOriginAccessIdentity }
