AWSTemplateFormatVersion: "2010-09-09"
Description: Terra Cloud
Resources:
    TerraS3:
        Type: AWS::S3::Bucket
    TerraECSCluster:
        Type: AWS::ECS::Cluster
        Properties:
            ClusterName: TerraCluster
    TerraECSService:
        Type: AWS::ECS::Service
        Properties:
            TaskDefinition: !REF TerraECSTaskDefinition
    TerraECSTaskDefinition:
        Type: AWS::ECS::TaskDefinition
        Properties:
            ContainerDefinitions:
                - ContainerDefinition:
                    Name: TerraElasticContainer
                    Image: 498848135448.dkr.ecr.us-east-1.amazonaws.com/terra-repo
